(()=>{
'use strict';
const css=`
#ari3d{position:fixed;left:20px;bottom:20px;z-index:2147483000;direction:ltr;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;pointer-events:none}
.ari3d-card{position:relative;display:flex;align-items:flex-end;gap:12px;pointer-events:auto;filter:drop-shadow(0 24px 55px rgba(0,0,0,.5))}
.ari3d-bubble{position:relative;width:min(310px,calc(100vw - 112px));padding:13px 15px;border:1px solid rgba(255,255,255,.15);border-radius:20px 20px 20px 6px;background:linear-gradient(145deg,rgba(13,17,29,.94),rgba(4,7,13,.9));backdrop-filter:blur(22px);box-shadow:inset 0 1px 0 rgba(255,255,255,.1),0 16px 60px rgba(0,0,0,.42);color:#e9edf6;font-size:11px;line-height:1.75;animation:ariIn .65s cubic-bezier(.2,.8,.2,1)}
.ari3d-bubble:after{content:"";position:absolute;right:-1px;bottom:12px;width:38%;height:1px;background:linear-gradient(90deg,transparent,rgba(169,140,255,.55),transparent);animation:scan 2.8s ease-in-out infinite}
.ari3d-bubble b{display:block;color:#fff;font-size:12px;margin-bottom:3px}.ari3d-actions{display:flex;gap:6px;margin-top:7px;flex-wrap:wrap}.ari3d-btn{border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.055);color:#cdd3df;border-radius:9px;padding:5px 8px;font-size:8px;cursor:pointer;transition:.22s}.ari3d-btn:hover{transform:translateY(-2px);background:rgba(169,140,255,.14);border-color:rgba(169,140,255,.5);color:#fff}
.ari3d-avatar{width:88px;height:112px;position:relative;flex:none;cursor:pointer;transform-style:preserve-3d;transition:transform .22s cubic-bezier(.2,.8,.2,1);animation:ariFloat 4.5s ease-in-out infinite}.ari3d-avatar:before{content:"";position:absolute;left:7px;bottom:-7px;width:72px;height:18px;border-radius:50%;background:radial-gradient(ellipse,rgba(126,99,255,.34),transparent 70%);filter:blur(5px);animation:ground 2.2s ease-in-out infinite}
.ari3d-glow{position:absolute;inset:8px -12px 0;border-radius:50%;background:radial-gradient(circle,rgba(137,112,255,.4),transparent 68%);filter:blur(13px);transform:translateZ(-24px)}.ari3d-aura{position:absolute;left:14px;top:3px;width:59px;height:59px;border:1px solid rgba(171,143,255,.48);border-radius:50%;box-shadow:0 0 32px rgba(126,99,255,.35),inset 0 0 22px rgba(126,99,255,.14);animation:ariSpin 8s linear infinite}.ari3d-aura:after{content:"";position:absolute;inset:8px;border:1px dashed rgba(90,174,255,.32);border-radius:50%;animation:ariSpin 5s linear infinite reverse}
.ari3d-body{position:absolute;left:20px;bottom:0;width:48px;height:51px;border-radius:17px 17px 13px 13px;background:linear-gradient(150deg,#b09aff 0%,#684fd0 52%,#262044 100%);border:1px solid rgba(255,255,255,.26);box-shadow:inset 8px 0 14px rgba(255,255,255,.12),0 10px 28px rgba(86,61,190,.4);transform:translateZ(5px)}.ari3d-body:after{content:"A";position:absolute;left:50%;top:14px;transform:translateX(-50%);font-weight:900;font-size:13px;color:#fff8;letter-spacing:.08em}
.ari3d-head{position:absolute;left:13px;top:19px;width:58px;height:58px;border-radius:22px 22px 25px 25px;background:radial-gradient(circle at 35% 24%,#fff 0 3%,#e8eaf1 4%,#b5bdce 31%,#667289 67%,#303848 100%);border:1px solid rgba(255,255,255,.42);box-shadow:inset -8px -9px 17px rgba(0,0,0,.3),0 8px 34px rgba(89,113,190,.34);transform:translateZ(25px)}
.ari3d-head:before{content:"";position:absolute;inset:9px 8px 11px;border-radius:16px;background:linear-gradient(160deg,rgba(12,16,27,.94),rgba(45,54,74,.84));border:1px solid rgba(255,255,255,.13);box-shadow:inset 0 0 18px rgba(90,174,255,.08)}
.ari3d-eye{position:absolute;top:29px;width:8px;height:10px;border-radius:50%;background:#fff;box-shadow:0 0 11px #9e88ff,0 0 24px rgba(110,94,255,.75);z-index:2;transition:transform .16s ease;animation:ariBlink 5s infinite}.ari3d-eye.l{left:27px}.ari3d-eye.r{right:27px}.ari3d-mouth{position:absolute;left:50%;top:42px;width:14px;height:6px;transform:translateX(-50%);border-bottom:2px solid #fff;border-radius:0 0 10px 10px;z-index:2;opacity:.8}.ari3d-antenna{position:absolute;left:42px;top:0;width:2px;height:22px;background:linear-gradient(#9c87ff,#fff);transform-origin:bottom;z-index:3;transition:.25s}.ari3d-antenna:before{content:"";position:absolute;left:50%;top:-6px;transform:translateX(-50%);width:9px;height:9px;border-radius:50%;background:#fff;box-shadow:0 0 14px #9b85ff,0 0 28px #735cff;animation:pulse 1.8s ease-in-out infinite}
.ari3d-arm{position:absolute;top:69px;width:19px;height:7px;border-radius:8px;background:#78839a;z-index:1;transition:.25s}.ari3d-arm.l{left:3px;transform:rotate(28deg)}.ari3d-arm.r{right:3px;transform:rotate(-28deg)}.ari3d-status{position:absolute;right:5px;top:13px;width:8px;height:8px;border-radius:50%;background:#59dda1;box-shadow:0 0 14px #59dda1;z-index:5}.ari3d-orb{position:absolute;left:4px;bottom:4px;width:7px;height:7px;border-radius:50%;background:#a98cff;box-shadow:0 0 17px #a98cff;animation:ariOrbit 2.6s linear infinite}
.ari3d-card[data-state=curious] .ari3d-eye{transform:translateY(-2px) scale(1.16)}.ari3d-card[data-state=proud] .ari3d-mouth{width:18px}.ari3d-card[data-state=thinking] .ari3d-antenna{transform:rotate(17deg)}.ari3d-card[data-state=goodbye] .ari3d-arm.r{animation:ariWave .55s ease-in-out 4}.ari3d-card[data-state=excited] .ari3d-avatar{animation:ariExcited .65s ease-in-out 2}.ari3d-card[data-state=excited] .ari3d-aura{border-color:rgba(90,174,255,.8)}
.ari3d-close{position:absolute;right:-5px;top:-9px;width:21px;height:21px;border-radius:50%;border:1px solid rgba(255,255,255,.16);background:#0b0e15;color:#aab0bd;font-size:12px;cursor:pointer}.ari3d-hidden{display:none!important}
@keyframes ariFloat{0%,100%{transform:translateY(0) rotateY(0)}50%{transform:translateY(-9px) rotateY(5deg)}}@keyframes ariSpin{to{transform:rotate(360deg)}}@keyframes ariBlink{0%,45%,48%,100%{transform:scaleY(1)}46%,47%{transform:scaleY(.12)}}@keyframes ariOrbit{to{transform:rotate(360deg) translateX(20px) rotate(-360deg)}}@keyframes ariWave{0%,100%{transform:rotate(-28deg)}50%{transform:rotate(-58deg)}}@keyframes ariIn{from{opacity:0;transform:translateY(12px) scale(.95)}to{opacity:1;transform:none}}@keyframes pulse{50%{transform:translateX(-50%) scale(1.25);opacity:.7}}@keyframes scan{50%{transform:translateX(-160%);opacity:.2}}@keyframes ground{50%{transform:scale(.78);opacity:.55}}@keyframes ariExcited{50%{transform:translateY(-12px) rotateZ(-3deg) scale(1.05)}}
@media(max-width:640px){#ari3d{left:9px;bottom:9px}.ari3d-bubble{width:calc(100vw - 100px);font-size:10px;padding:10px 11px}.ari3d-avatar{width:66px;height:86px;transform:scale(.88);transform-origin:bottom left}.ari3d-head{transform:scale(.88) translateZ(15px);transform-origin:top left}.ari3d-body{transform:scale(.88);transform-origin:bottom left}.ari3d-aura{transform:scale(.88);transform-origin:top left}.ari3d-antenna{transform:scale(.88);transform-origin:bottom}.ari3d-arm{transform:scale(.88)}.ari3d-card{gap:5px}}
@media(prefers-reduced-motion:reduce){#ari3d *{animation:none!important;transition:none!important}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const root=document.createElement('div');root.id='ari3d';root.innerHTML=`<div class="ari3d-card" data-state="hello"><div class="ari3d-bubble"><button class="ari3d-close" aria-label="Hide Ari">×</button><b>Ari 3D · ONLINE ✦</b><span id="ari3d-text">سلام! من آری‌ام 😎 آماده‌ای بریم داخل Universe؟</span><div class="ari3d-actions"><button class="ari3d-btn" data-state="curious">پروژه‌ها 👀</button><button class="ari3d-btn" data-state="proud">توانایی‌ها ⚡</button><button class="ari3d-btn" data-state="thinking">راهنما 🧠</button></div></div><div class="ari3d-avatar" aria-label="Ari 3D"><div class="ari3d-glow"></div><div class="ari3d-aura"></div><div class="ari3d-antenna"></div><div class="ari3d-status"></div><div class="ari3d-head"><i class="ari3d-eye l"></i><i class="ari3d-eye r"></i><i class="ari3d-mouth"></i></div><div class="ari3d-body"></div><div class="ari3d-arm l"></div><div class="ari3d-arm r"></div><div class="ari3d-orb"></div></div></div>`;document.body.appendChild(root);
const card=root.querySelector('.ari3d-card'),text=root.querySelector('#ari3d-text'),avatar=root.querySelector('.ari3d-avatar'),eyes=[...root.querySelectorAll('.ari3d-eye')];
const messages={hello:'سلام! من آری‌ام 😎 آماده‌ای بریم داخل Universe؟',curious:'خب خب… رسیدیم به قسمت خوشمزه ماجرا 👀 پروژه‌ها رو ببین؛ اینجا شعار کمتره، چیز ساخته‌شده بیشتره.',proud:'این بخش جاییه که تکنولوژی‌ها تبدیل به تجربه می‌شن. تمیز، سریع و بدون ادا ⚡',thinking:'من راهنما هستم، نه مزاحم. هرجا لازم باشه کوتاه میام کنار تا خود پروژه بدرخشه 🧠',goodbye:'فعلاً حاجی 👋 من همین دور و بر Universe هستم.',excited:'عه! 👀 اینجا همون جاییه که باید یکم بیشتر زوم کنیم روی جزئیات.'};
function setState(s,msg){card.dataset.state=s;text.textContent=msg||messages[s]||messages.hello;}
root.querySelectorAll('[data-state]').forEach(b=>b.addEventListener('click',e=>{const s=e.currentTarget.dataset.state;setState(s);if(s==='curious')document.querySelector('#projects')?.scrollIntoView({behavior:'smooth'});if(s==='proud')document.querySelector('#stack')?.scrollIntoView({behavior:'smooth'});}));
avatar.addEventListener('click',()=>setState('excited'));
root.querySelector('.ari3d-close').addEventListener('click',()=>root.classList.add('ari3d-hidden'));
let raf=0,mx=0,my=0;document.addEventListener('mousemove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;avatar.style.transform=`translate3d(${mx*3}px,${my*-4}px,0) rotateY(${mx*10}deg) rotateX(${my*-5}deg)`;eyes.forEach((eye,i)=>eye.style.translate=`${mx*(i?2:-2)}px ${my*1.5}px`);});},{passive:true});
const observer=new IntersectionObserver(es=>es.forEach(en=>{if(!en.isIntersecting)return;const id=en.target.id;if(id==='projects')setState('curious');else if(id==='stack')setState('proud');else if(id==='security')setState('thinking','امنیت هم باید بخشی از تجربه باشد؛ نه یک برچسب تزئینی 🛡️');else if(id==='contact')setState('goodbye');}),{threshold:.45});document.querySelectorAll('section[id]').forEach(s=>observer.observe(s));
})();