(()=>{'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],root=document.documentElement;
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const loader=$('#loader');setTimeout(()=>{if(loader){loader.style.opacity='0';loader.style.pointerEvents='none';setTimeout(()=>loader.remove(),700)}},reduce?180:850);
let ticking=false;const updateScroll=()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),p=Math.min(1,scrollY/max);root.style.setProperty('--progress',p);root.style.setProperty('--scrollY',scrollY);if(!ticking){requestAnimationFrame(()=>{const hero=$('#heroStage');if(hero&&!reduce){const y=Math.min(1,scrollY/innerHeight);hero.style.setProperty('--scroll-scale',String(1-y*.12));hero.style.setProperty('--scroll-y',`${y*55}px`);hero.style.setProperty('--scroll-rot',`${y*4}deg`)}ticking=false})}ticking=true};addEventListener('scroll',updateScroll,{passive:true});updateScroll();
const cursor=$('.cursor');if(cursor&&!reduce&&innerWidth>900){let x=innerWidth/2,y=innerHeight/2,cx=x,cy=y;addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY;root.style.setProperty('--mx',`${x}px`);root.style.setProperty('--my',`${y}px`)},{passive:true});const loop=()=>{cx+=(x-cx)*.18;cy+=(y-cy)*.18;cursor.style.left=cx+'px';cursor.style.top=cy+'px';requestAnimationFrame(loop)};loop();$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/r.width,dy=(e.clientY-r.top-r.height/2)/r.height;el.style.transform=`translate3d(${dx*7}px,${dy*6}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(el=>io.observe(el));
const stage=$('#heroStage');if(stage&&!reduce){stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect(),x=e.clientX/r.width-(r.left/r.width)-.5,y=(e.clientY-r.top)/r.height-.5;stage.style.setProperty('--rx',`${y*-5}deg`);stage.style.setProperty('--ry',`${x*7}deg`)});stage.addEventListener('pointerleave',()=>{stage.style.setProperty('--rx','0deg');stage.style.setProperty('--ry','0deg')})}
const menu=$('#menu'),toggle=$('.menu-toggle');toggle?.addEventListener('click',()=>{const open=!menu.classList.contains('open');menu.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open))});$$('#menu a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
const navLinks=$$('#menu a'),sections=navLinks.map(a=>$(a.getAttribute('href'))).filter(Boolean);const navIO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>navIO.observe(s));
const secData={red:{k:'RED TEAM',t:'OFFENSIVE SECURITY',x:'بررسی سطح حمله، تست امنیت وب و شناسایی ریسک‌های قابل‌اثبات در محیط مجاز پروژه.',p:['Attack Surface Review','Web Security Testing','Threat Modeling'],n:'01'},blue:{k:'BLUE TEAM',t:'DEFENSIVE SECURITY',x:'طراحی کنترل‌های دفاعی، مشاهده‌پذیری، تحلیل لاگ و پاسخ به رخداد با تمرکز بر کاهش ریسک.',p:['Threat Detection','Log Analysis','Incident Response'],n:'02'},purple:{k:'PURPLE TEAM',t:'SECURITY VALIDATION',x:'اتصال حمله و دفاع: سنجش اینکه کنترل‌های دفاعی واقعاً سناریوهای مدل‌شده را تشخیص می‌دهند یا نه.',p:['Detection Engineering','Attack → Detect → Fix','Security Validation'],n:'03'},dev:{k:'DEVSECOPS',t:'SECURE SHIP',x:'امنیت را وارد چرخه توسعه می‌کنیم؛ از code review و dependency hygiene تا CI/CD security.',p:['Secure Development','Dependency Security','Security Automation'],n:'04'}};
const setSec=k=>{const d=secData[k];if(!d)return;const panel=$('#securityPanel');panel?.setAttribute('data-mode',k);$('#secKicker').textContent=d.k;$('#secTitle').textContent=d.t;$('#secText').textContent=d.x;$('#secIndex').textContent=d.n;const box=$('#secPoints');box.replaceChildren(...d.p.map(t=>{const b=document.createElement('b');b.textContent=t;return b}));$$('.sec-tab').forEach(b=>{const on=b.dataset.sec===k;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))})};$$('.sec-tab').forEach(b=>b.addEventListener('click',()=>setSec(b.dataset.sec)));
const modes={fluid:['01 / FLUID DESIGN','LAYOUT THAT BREATHES.','عرض، فاصله و ساختار به اندازه viewport و محتوای واقعی واکنش نشان می‌دهند.'],minimal:['02 / MINIMAL DESIGN','LESS. MORE INTENT.','هر عنصر دلیل دارد؛ hierarchy و content قبل از decoration قرار می‌گیرند.'],dynamic:['03 / DYNAMIC DESIGN','INTERACTION WITH PURPOSE.','تعامل‌ها برای راهنمایی کاربر، بازخورد و کشف محتوا استفاده می‌شوند.'],progressive:['04 / PROGRESSIVE','WEB THAT FEELS LIKE A PRODUCT.','تجربه از progressive enhancement شروع می‌شود و با قابلیت‌های واقعی رشد می‌کند.'],responsive:['05 / RESPONSIVE','ONE SYSTEM. MANY SCREENS.','سیستم layout از موبایل تا نمایشگرهای بزرگ رفتار قابل پیش‌بینی دارد.'],fixed:['06 / FIXED','CONTROLLED PRECISION.','در جایی که کنترل بصری مهم است، grid و rhythm دقیق نگه داشته می‌شوند.']};$$('.lab-mode').forEach(b=>b.addEventListener('click',()=>{const d=modes[b.dataset.mode];if(!d)return;$$('.lab-mode').forEach(x=>x.classList.toggle('active',x===b));const stage=$('#labStage');stage?.setAttribute('data-mode',b.dataset.mode);$('#labKicker').textContent=d[0];$('#labTitle').textContent=d[1];$('#labText').textContent=d[2];$('#labNumber').textContent=d[0].slice(0,2)}));
const cases={portfolio:{k:'01 / WEB EXPERIENCE',t:'ARSHIA PORTFOLIO',parts:[['CONTEXT','یک پورتفولیوی شخصی باید در چند ثانیه هویت، توانایی و مسیر مشاهده پروژه‌ها را منتقل کند.'],['THINKING','به‌جای رزومه‌ی متنی، تجربه را به یک روایت تعاملی با hierarchy روشن تبدیل کردم.'],['BUILD','Static-first HTML/CSS/JavaScript، typography سفارشی، SVG/CSS depth، motion کنترل‌شده و responsive behavior.'],['RESULT','این یک Personal Project است؛ نتیجه تجاری یا KPI ساختگی برای آن ادعا نمی‌شود.'],['LESSON','افکت وقتی ارزش دارد که navigation، hierarchy یا perception را بهتر کند.']]},social:{k:'02 / SOCIAL COMMERCE · CONCEPT',t:'SOCIAL COMMERCE',parts:[['CONTEXT','یک مفهوم محتوایی برای شبکه‌های اجتماعی که هدفش حرکت از توجه به اقدام است.'],['THINKING','محتوا، ادیت و CTA به‌عنوان یک funnel ساده دیده می‌شوند؛ نه سه خروجی جدا.'],['BUILD','ساختار Reel/Story، پیام کوتاه، visual hierarchy و CTAهای واضح در یک concept system.'],['RESULT','Concept Project است و فروش، conversion یا client result واقعی ادعا نمی‌شود.'],['LESSON','قبل از ساخت محتوا باید action مورد انتظار مخاطب روشن باشد.']]},dana:{k:'03 / AI PRODUCT · CONCEPT',t:'DANA CONCEPT',parts:[['CONTEXT','یک concept برای محصول دیجیتال با تمرکز بر interface و AI-assisted workflows.'],['THINKING','ابتدا جریان کاربر و معماری اطلاعات، سپس لایه AI؛ نه AI به‌عنوان تزئین.'],['BUILD','React/Next.js concepts، UI patterns و تعاملات آزمایشی.'],['RESULT','Prototype/Concept است؛ هیچ metric یا نتیجه محصول واقعی ادعا نمی‌شود.'],['LESSON','AI زمانی ارزشمند است که یک مرحله واقعی از workflow را بهتر کند.']]}};
const modal=$('#caseModal'),mTitle=$('#modalTitle'),mKicker=$('#modalKicker'),mBody=$('#modalBody'),close=()=>{modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.style.overflow=''};$$('[data-open]').forEach(btn=>btn.addEventListener('click',()=>{const d=cases[btn.dataset.open];if(!d)return;mKicker.textContent=d.k;mTitle.textContent=d.t;mBody.replaceChildren(...d.parts.map(([a,b])=>{const s=document.createElement('section');s.className='modal-section';const h=document.createElement('b');h.textContent=a;const p=document.createElement('p');p.textContent=b;s.append(h,p);return s}));modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#modalClose')?.focus()}));$('#modalClose')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});addEventListener('keydown',e=>{if(e.key==='Escape')close()});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const target=$(id);if(target){e.preventDefault();target.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}}));
})();